console.log("Arithmetic Operators");
let a=5;
let b=5;
console.log("Addition " + (a+b));
console.log("Subtraction " + (a-b));
console.log("Multiplication " + (a*b));
console.log("Division " + (a/b));
console.log("Exponentiation " + (2**3));
console.log("Modulus " + (a%b));
console.log("Increment " + (a++));
console.log("Decrement " + (a--));